CREATE TABLE USUARIO (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    rut VARCHAR(20) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    EMPRESA_id BIGINT NOT NULL,
    ROL_id BIGINT NOT NULL,
    SUCURSAL_id BIGINT NOT NULL
);