
CREATE TABLE ESTADO_SUSCRIPCION (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre_estado VARCHAR(50) NOT NULL
);

CREATE TABLE DIA_SEMANA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre_dia_semana VARCHAR(20) NOT NULL
);

CREATE TABLE TIPO_MARCAJE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre_tipo_marcaje VARCHAR(50) NOT NULL
);

CREATE TABLE EMPRESA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    rut_empresa VARCHAR(20) UNIQUE NOT NULL,
    razon_social VARCHAR(100) NOT NULL,
    logo_url VARCHAR(255),
    color_primario VARCHAR(7),
    ESTADO_SUSCRIPCION_id INT NOT NULL,
    FOREIGN KEY (ESTADO_SUSCRIPCION_id) REFERENCES ESTADO_SUSCRIPCION(id)
);

CREATE TABLE SUCURSAL (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    direccion VARCHAR(200),
    latitud_centro DECIMAL(10,8),
    longitud_centro DECIMAL(11,8),
    radio_tolerancia_metros INT,
    EMPRESA_id INT NOT NULL,
    FOREIGN KEY (EMPRESA_id) REFERENCES EMPRESA(id) ON DELETE CASCADE
);

CREATE TABLE ROL (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre_rol VARCHAR(50) NOT NULL,
    descripcion VARCHAR(255),
    EMPRESA_id INT NOT NULL,
    FOREIGN KEY (EMPRESA_id) REFERENCES EMPRESA(id) ON DELETE CASCADE
);

CREATE TABLE USUARIO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    rut VARCHAR(20) UNIQUE NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    EMPRESA_id INT NOT NULL,
    ROL_id INT NOT NULL,
    SUCURSAL_id INT,
    FOREIGN KEY (EMPRESA_id) REFERENCES EMPRESA(id) ON DELETE CASCADE,
    FOREIGN KEY (ROL_id) REFERENCES ROL(id),
    FOREIGN KEY (SUCURSAL_id) REFERENCES SUCURSAL(id)
);


CREATE TABLE BIOMETRIA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    vector_facial LONGTEXT, 
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USUARIO_id INT NOT NULL UNIQUE,
    FOREIGN KEY (USUARIO_id) REFERENCES USUARIO(id) ON DELETE CASCADE
);

CREATE TABLE HORARIO_TURNO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    hora_entrada TIME NOT NULL, 
    hora_salida TIME NOT NULL,
    USUARIO_id INT NOT NULL,
    DIA_SEMANA_id INT NOT NULL,
    FOREIGN KEY (USUARIO_id) REFERENCES USUARIO(id) ON DELETE CASCADE,
    FOREIGN KEY (DIA_SEMANA_id) REFERENCES DIA_SEMANA(id)
);

CREATE TABLE ASISTENCIA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fecha_hora_marcaje TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    latitud_marca DECIMAL(10,8),
    longitud_marca DECIMAL(11,8),
    validacion_biometrica CHAR(1) DEFAULT '0', 
    validacion_gps CHAR(1) DEFAULT '0', 
    USUARIO_id INT NOT NULL,
    TIPO_MARCAJE_id INT NOT NULL,
    FOREIGN KEY (USUARIO_id) REFERENCES USUARIO(id) ON DELETE CASCADE,
    FOREIGN KEY (TIPO_MARCAJE_id) REFERENCES TIPO_MARCAJE(id)
);


INSERT INTO ESTADO_SUSCRIPCION (nombre_estado) VALUES ('ACTIVO'), ('SUSPENDIDO'), ('PRUEBA_GRATIS');


INSERT INTO DIA_SEMANA (nombre_dia_semana) VALUES ('LUNES'), ('MARTES'), ('MIÉRCOLES'), ('JUEVES'), ('VIERNES'), ('SÁBADO'), ('DOMINGO');


INSERT INTO TIPO_MARCAJE (nombre_tipo_marcaje) VALUES ('ENTRADA'), ('SALIDA'), ('INICIO_COLACION'), ('FIN_COLACION');