CREATE TABLE dia_semana (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(20) NOT NULL UNIQUE
);
CREATE TABLE horario_turno (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
hora_entrada VARCHAR(10) NOT NULL,
hora_salida VARCHAR(10) NOT NULL,
USUARIO_id BIGINT NOT NULL,
DIA_SEMANA_id BIGINT NOT NULL,
CONSTRAINT fk_horario_dia_semana FOREIGN KEY (DIA_SEMANA_id) REFERENCES dia_semana(id)
);