CREATE TABLE horario_turno (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    hora_entrada VARCHAR(10) NOT NULL,
    hora_salida VARCHAR(10) NOT NULL,
    USUARIO_id BIGINT NOT NULL,
    DIA_SEMANA_id BIGINT NOT NULL
);